import type {
  Conversation,
  Invoice,
  NegotiationMessage,
  Product,
  RestockRecommendation,
  Supplier,
  ThresholdChangeRequest,
  TimelineEvent,
  Workflow,
} from "@/lib/types"

export const mockSuppliers: Supplier[] = [
  {
    id: "sup-001",
    name: "Northstar Foods",
    region: "US West",
    reliabilityScore: 94,
    leadTimeDays: 5,
    status: "preferred",
  },
  {
    id: "sup-002",
    name: "Harbor Beverage Co.",
    region: "US Central",
    reliabilityScore: 79,
    leadTimeDays: 8,
    status: "watchlist",
  },
  {
    id: "sup-003",
    name: "Pacific Snacks Supply",
    region: "US West",
    reliabilityScore: 89,
    leadTimeDays: 4,
    status: "preferred",
  },
  {
    id: "sup-004",
    name: "Evergreen Household Goods",
    region: "US East",
    reliabilityScore: 86,
    leadTimeDays: 6,
    status: "preferred",
  },
]

export const mockProducts: Product[] = [
  {
    id: "prod-001",
    sku: "SKU-ALM-8842",
    name: "Almond Protein Bar 12ct",
    category: "Packaged Goods",
    stockOnHand: 418,
    currentThreshold: 520,
    unitCost: 18.4,
    maxStockAmount: 1500,
    forecastDemand: 680,
    monthlyVelocity: 1260,
    trend30d: -18,
    trend365d: 9,
    supplierId: "sup-001",
    conversationId: "conv-1001",
    invoiceId: "inv-7001",
    status: "near-threshold",
    suppliers: [
      {
        supplierId: "sup-001",
        lastDealPrice: 18.4,
        lastDealDate: "2026-03-22",
        leadTimeDays: 5,
        moq: 480,
        reliabilityScore: 94,
        preferred: true,
        note: "Primary · 3.2% volume rebate on 600+ units",
      },
      {
        supplierId: "sup-003",
        lastDealPrice: 18.9,
        lastDealDate: "2026-01-08",
        leadTimeDays: 4,
        moq: 360,
        reliabilityScore: 89,
        preferred: false,
        note: "Alternate · shorter lead time, no rebate tier",
      },
    ],
  },
  {
    id: "prod-002",
    sku: "SKU-CFE-1290",
    name: "Cold Brew Concentrate 1L",
    category: "Beverages",
    stockOnHand: 96,
    currentThreshold: 210,
    unitCost: 22.75,
    maxStockAmount: 640,
    forecastDemand: 380,
    monthlyVelocity: 840,
    trend30d: -31,
    trend365d: 22,
    supplierId: "sup-002",
    conversationId: "conv-1002",
    invoiceId: "inv-7002",
    status: "below-threshold",
    suppliers: [
      {
        supplierId: "sup-002",
        lastDealPrice: 22.75,
        lastDealDate: "2026-03-30",
        leadTimeDays: 8,
        moq: 300,
        reliabilityScore: 79,
        preferred: true,
        note: "Primary · currently pushing +6% surcharge",
      },
      {
        supplierId: "sup-001",
        lastDealPrice: 23.4,
        lastDealDate: "2025-11-12",
        leadTimeDays: 6,
        moq: 240,
        reliabilityScore: 94,
        preferred: false,
        note: "Backup · higher spot price but stable on allocations",
      },
    ],
  },
  {
    id: "prod-003",
    sku: "SKU-SNP-4471",
    name: "Sea Salt Plantain Chips",
    category: "Snacks",
    stockOnHand: 740,
    currentThreshold: 560,
    unitCost: 9.8,
    maxStockAmount: 1800,
    forecastDemand: 610,
    monthlyVelocity: 980,
    trend30d: 6,
    trend365d: 14,
    supplierId: "sup-003",
    conversationId: "conv-1003",
    invoiceId: "inv-7003",
    status: "healthy",
  },
  {
    id: "prod-004",
    sku: "SKU-LND-3021",
    name: "Citrus Laundry Sheets 60ct",
    category: "Household",
    stockOnHand: 188,
    currentThreshold: 330,
    unitCost: 12.35,
    maxStockAmount: 900,
    forecastDemand: 420,
    monthlyVelocity: 690,
    trend30d: -24,
    trend365d: 7,
    supplierId: "sup-004",
    conversationId: "conv-1004",
    invoiceId: "inv-7004",
    status: "batch-candidate",
  },
  {
    id: "prod-005",
    sku: "SKU-RCE-7740",
    name: "Jasmine Rice 5kg",
    category: "Pantry",
    stockOnHand: 58,
    currentThreshold: 180,
    unitCost: 16.1,
    maxStockAmount: 720,
    forecastDemand: 290,
    monthlyVelocity: 540,
    trend30d: -37,
    trend365d: 18,
    supplierId: "sup-001",
    conversationId: "conv-1005",
    invoiceId: "inv-7001",
    status: "below-threshold",
    suppliers: [
      {
        supplierId: "sup-001",
        lastDealPrice: 16.1,
        lastDealDate: "2026-02-18",
        leadTimeDays: 5,
        moq: 200,
        reliabilityScore: 94,
        preferred: true,
        note: "Primary · bundleable with Almond Protein Bar PO",
      },
      {
        supplierId: "sup-003",
        lastDealPrice: 15.7,
        lastDealDate: "2025-12-02",
        leadTimeDays: 4,
        moq: 150,
        reliabilityScore: 89,
        preferred: false,
        note: "Alternate · cheaper spot, freight surcharge applies",
      },
    ],
  },
]

export const mockConversations: Conversation[] = [
  {
    id: "conv-1001",
    productSku: "SKU-ALM-8842",
    linkedSkus: ["SKU-ALM-8842", "SKU-RCE-7740"],
    supplierId: "sup-001",
    subject: "Expedite next protein bar shipment",
    source: "Email",
    negotiationState: "Counter Offer Suggested",
    latestMessage: "Can confirm 1,200 cases this week with revised payment terms.",
    targetPriceRange: "$17.90 - $18.25 per case",
    createdDate: "2026-04-18",
    status: "negotiating",
    priority: "high",
    lastMessageAt: "2026-04-19T06:40:00.000Z",
    aiExtraction: {
      extractedPrice: "$18.40 per case",
      extractedQuantity: "1,200 cases",
      deliveryEstimate: "Apr 24 - Apr 26",
      supplierLanguage: "English",
      detectedIntent: "Accept with payment term adjustment",
      missingFields: ["Freight surcharge confirmation"],
      confidenceScore: 91,
    },
    nextAction: {
      recommendedNextStep: "Generate counter offer with net-30 terms and bundled rice allocation.",
      negotiationSummary:
        "Supplier can meet quantity but wants adjusted payment terms. Batch with Jasmine Rice improves freight utilization.",
      linkedInvoiceStatus: "Waiting approval",
    },
  },
  {
    id: "conv-1002",
    productSku: "SKU-CFE-1290",
    linkedSkus: ["SKU-CFE-1290"],
    supplierId: "sup-002",
    subject: "Cold brew shortage and split delivery terms",
    source: "WhatsApp",
    negotiationState: "Needs Analysis",
    latestMessage: "Supplier proposed split shipment at $22.75 without a freight cap; price breaches the negotiated ceiling.",
    targetPriceRange: "$21.90 - $22.50 per unit",
    createdDate: "2026-04-19",
    status: "needs-reply",
    priority: "critical",
    lastMessageAt: "2026-04-19T05:55:00.000Z",
    aiExtraction: {
      extractedPrice: "$22.75 per unit",
      extractedQuantity: "480 units",
      deliveryEstimate: "Apr 23 and Apr 29 split",
      supplierLanguage: "English",
      detectedIntent: "Propose split delivery with price hold",
      missingFields: ["Freight cap", "Second shipment quantity"],
      confidenceScore: 93,
    },
    nextAction: {
      recommendedNextStep: "Cold brew is 114 units below current threshold. Push supplier to cap freight and lock the second shipment before accepting the split.",
      negotiationSummary:
        "Supplier's unit price exceeds the negotiated ceiling and freight is uncapped, exposing the invoice to further variance.",
      linkedInvoiceStatus: "Needs review",
    },
  },
  {
    id: "conv-1003",
    productSku: "SKU-SNP-4471",
    linkedSkus: ["SKU-SNP-4471"],
    supplierId: "sup-003",
    subject: "Confirm promo month reserve allocation",
    source: "WeChat",
    negotiationState: "Closed",
    latestMessage: "确认双十一档期已预留900箱,第46周发货,价格维持不变。",
    targetPriceRange: "$9.40 - $9.75 per carton",
    createdDate: "2026-04-17",
    status: "resolved",
    priority: "medium",
    lastMessageAt: "2026-04-18T23:15:00.000Z",
    aiExtraction: {
      extractedPrice: "$9.80 per carton",
      extractedQuantity: "900 cartons",
      deliveryEstimate: "Week 46 reserve",
      supplierLanguage: "中文 (Simplified Chinese)",
      detectedIntent: "Reserve campaign allocation",
      missingFields: ["Final allocation date"],
      confidenceScore: 84,
    },
    nextAction: {
      recommendedNextStep: "Keep closed packet available for completed invoice history.",
      negotiationSummary:
        "Supplier allocation, invoice validation, and settlement packet are complete.",
      linkedInvoiceStatus: "Completed",
    },
  },
  {
    id: "conv-1004",
    productSku: "SKU-LND-3021",
    linkedSkus: ["SKU-LND-3021"],
    supplierId: "sup-004",
    subject: "Laundry sheets MOQ adjustment",
    source: "Telegram",
    negotiationState: "Accepted",
    latestMessage: "MOQ例外承認済み。620パック、4月28日納期、単価$12.20で対応可能です。",
    targetPriceRange: "$12.00 - $12.40 per pack",
    createdDate: "2026-04-16",
    status: "resolved",
    priority: "low",
    lastMessageAt: "2026-04-18T17:20:00.000Z",
    aiExtraction: {
      extractedPrice: "$12.35 per pack",
      extractedQuantity: "620 packs",
      deliveryEstimate: "Apr 28",
      supplierLanguage: "日本語 (Japanese)",
      detectedIntent: "Accept MOQ exception",
      missingFields: [],
      confidenceScore: 96,
    },
    nextAction: {
      recommendedNextStep: "Attach accepted MOQ sheet to invoice exception packet.",
      negotiationSummary:
        "MOQ adjustment is accepted and ready to unblock the invoice management workflow.",
      linkedInvoiceStatus: "Blocked",
    },
  },
  {
    id: "conv-1005",
    productSku: "SKU-RCE-7740",
    linkedSkus: ["SKU-RCE-7740", "SKU-ALM-8842"],
    supplierId: "sup-001",
    subject: "Rice reorder bundle · supplier offered two delivery dates",
    source: "WhatsApp",
    negotiationState: "Escalated",
    latestMessage: "Supplier committed to a bundle price only if full pallet, with two contradictory delivery dates (Apr 25 or Apr 30).",
    targetPriceRange: "$15.80 - $16.25 per bag",
    createdDate: "2026-04-19",
    status: "needs-reply",
    priority: "critical",
    lastMessageAt: "2026-04-19T08:10:00.000Z",
    aiExtraction: {
      extractedPrice: "$16.10 per bag (conditional on full pallet)",
      extractedQuantity: "700 bags",
      deliveryEstimate: "Apr 25 or Apr 30 (supplier offered both)",
      supplierLanguage: "English",
      detectedIntent: "Bundle rice with protein bar shipment",
      missingFields: ["Confirmed delivery date", "Bundle discount"],
      confidenceScore: 92,
    },
    nextAction: {
      recommendedNextStep: "Rice is 122 units below current threshold. Force supplier to lock a single delivery date and confirm bundle discount before approving.",
      negotiationSummary:
        "Z.AI parsed the voice note with high confidence, but the supplier's terms contain two conflicting delivery dates and a conditional pallet price — resolution needs merchant intervention.",
      linkedInvoiceStatus: "Waiting approval",
    },
  },
]

export const mockNegotiationMessages: NegotiationMessage[] = [
  {
    id: "msg-po-1001",
    conversationId: "conv-1001",
    supplierId: "sup-001",
    type: "merchant-action",
    author: "merchant",
    body: "Restock order generated by Z.AI and sent to Northstar Foods. Please confirm quantity, target price, and delivery by Apr 24.",
    sentiment: "neutral",
    createdAt: "2026-04-18T09:00:00.000Z",
    attachmentType: "pdf",
    attachmentLabel: "PO-1001-northstar-protein-bars.pdf",
    orderSummary: {
      poNumber: "PO-1001",
      issuedAt: "2026-04-18",
      items: [
        {
          sku: "SKU-ALM-8842",
          productName: "Almond Protein Bar 12ct",
          quantity: 1200,
          unit: "case",
          unitPrice: "$18.08",
          lineTotal: "$21,696.00",
        },
      ],
      subtotal: "$21,696.00",
      total: "$21,900.00",
      deliveryBy: "Apr 26, 2026",
      paymentTerms: "Net 30",
      notes: "Bundle with Jasmine Rice pallet if freight space allows.",
    },
  },
  {
    id: "msg-po-1002",
    conversationId: "conv-1002",
    supplierId: "sup-002",
    type: "merchant-action",
    author: "merchant",
    body: "Restock order generated by Z.AI and sent to Harbor Beverage Co. Freight cap and shipment schedule requested.",
    sentiment: "neutral",
    createdAt: "2026-04-19T03:00:00.000Z",
    attachmentType: "pdf",
    attachmentLabel: "PO-1002-harbor-cold-brew.pdf",
    orderSummary: {
      poNumber: "PO-1002",
      issuedAt: "2026-04-19",
      items: [
        {
          sku: "SKU-CFE-1290",
          productName: "Cold Brew Concentrate 1L",
          quantity: 480,
          unit: "unit",
          unitPrice: "$22.20",
          lineTotal: "$10,656.00",
        },
      ],
      subtotal: "$10,656.00",
      total: "$10,800.00",
      deliveryBy: "Apr 23, 2026",
      paymentTerms: "Net 15",
      notes: "Freight must be capped. Split shipment only if cap is honored.",
    },
  },
  {
    id: "msg-po-1003",
    conversationId: "conv-1003",
    supplierId: "sup-003",
    type: "merchant-action",
    author: "merchant",
    body: "Restock order generated by Z.AI and sent to Pacific Snacks Supply for 11.11 promo allocation.",
    sentiment: "neutral",
    createdAt: "2026-04-17T10:00:00.000Z",
    attachmentType: "pdf",
    attachmentLabel: "PO-1003-pacific-promo-reserve.pdf",
    orderSummary: {
      poNumber: "PO-1003",
      issuedAt: "2026-04-17",
      items: [
        {
          sku: "SKU-SNP-4471",
          productName: "Multigrain Crackers 200g",
          quantity: 900,
          unit: "carton",
          unitPrice: "$9.58",
          lineTotal: "$8,622.00",
        },
      ],
      subtotal: "$8,622.00",
      total: "$8,800.00",
      deliveryBy: "Week 46 reserve window",
      paymentTerms: "Net 30",
      notes: "Promo allocation must be reserved before the 11.11 campaign lock date.",
    },
  },
  {
    id: "msg-po-1004",
    conversationId: "conv-1004",
    supplierId: "sup-004",
    type: "merchant-action",
    author: "merchant",
    body: "Restock order generated by Z.AI and sent to Evergreen Household Goods with MOQ exception request.",
    sentiment: "neutral",
    createdAt: "2026-04-16T10:00:00.000Z",
    attachmentType: "pdf",
    attachmentLabel: "PO-1004-evergreen-laundry-sheets.pdf",
    orderSummary: {
      poNumber: "PO-1004",
      issuedAt: "2026-04-16",
      items: [
        {
          sku: "SKU-LND-3021",
          productName: "Citrus Laundry Sheets 60ct",
          quantity: 620,
          unit: "pack",
          unitPrice: "$12.20",
          lineTotal: "$7,564.00",
        },
      ],
      subtotal: "$7,564.00",
      total: "$7,700.00",
      deliveryBy: "Apr 28, 2026",
      paymentTerms: "Net 30",
      notes: "MOQ exception requested from regional sales.",
    },
  },
  {
    id: "msg-po-1005",
    conversationId: "conv-1005",
    supplierId: "sup-001",
    type: "merchant-action",
    author: "merchant",
    body: "Restock order generated by Z.AI and sent to Northstar Foods as a bundled rice + protein bar pallet.",
    sentiment: "neutral",
    createdAt: "2026-04-19T06:00:00.000Z",
    attachmentType: "pdf",
    attachmentLabel: "PO-1005-northstar-rice-bundle.pdf",
    orderSummary: {
      poNumber: "PO-1005",
      issuedAt: "2026-04-19",
      items: [
        {
          sku: "SKU-RCE-7740",
          productName: "Jasmine Rice 5kg",
          quantity: 700,
          unit: "bag",
          unitPrice: "$16.10",
          lineTotal: "$11,270.00",
        },
        {
          sku: "SKU-ALM-8842",
          productName: "Almond Protein Bar 12ct",
          quantity: 300,
          unit: "case",
          unitPrice: "$18.08",
          lineTotal: "$5,424.00",
        },
      ],
      subtotal: "$16,694.00",
      total: "$16,900.00",
      deliveryBy: "Apr 25, 2026",
      paymentTerms: "Net 30",
      notes: "Bundle shipment assumes full-pallet price lock.",
    },
  },
  {
    id: "msg-001",
    conversationId: "conv-1002",
    supplierId: "sup-002",
    type: "ai-interpretation",
    author: "ai",
    body: "Suggested counteroffer keeps unit cost flat if delivery moves to a split shipment.",
    sentiment: "positive",
    createdAt: "2026-04-19T05:55:00.000Z",
    attachmentType: "screenshot",
    attachmentLabel: "chat-screenshot-apr19.png",
  },
  {
    id: "msg-002",
    conversationId: "conv-1001",
    supplierId: "sup-001",
    type: "supplier-message",
    author: "supplier",
    body: "Can confirm 1,200 cases this week with revised payment terms.",
    sentiment: "neutral",
    createdAt: "2026-04-19T03:30:00.000Z",
    attachmentType: "email",
    attachmentLabel: "Email thread from Northstar Foods",
  },
  {
    id: "msg-004",
    conversationId: "conv-1002",
    supplierId: "sup-002",
    type: "supplier-message",
    author: "supplier",
    body: "We can split delivery: first truck Apr 23, second truck likely Apr 29. Freight depends on final route.",
    sentiment: "risk",
    createdAt: "2026-04-19T05:44:00.000Z",
    attachmentType: "image",
    attachmentLabel: "route-board-photo.jpg",
  },
  {
    id: "msg-005",
    conversationId: "conv-1002",
    supplierId: "sup-002",
    type: "ai-recommendation",
    author: "ai",
    body: "Request freight cap and second shipment quantity before accepting. Current invoice exposure is not bounded.",
    sentiment: "risk",
    createdAt: "2026-04-19T05:58:00.000Z",
  },
  {
    id: "msg-007",
    conversationId: "conv-1005",
    supplierId: "sup-001",
    type: "supplier-message",
    author: "supplier",
    body: "Voice note transcription: We can add rice to the protein bar truck, maybe Apr 25, maybe Apr 30, price stays sixteen ten if full pallet.",
    sentiment: "risk",
    createdAt: "2026-04-19T08:10:00.000Z",
    attachmentType: "voice",
    attachmentLabel: "rice-bundle-voice-note.m4a",
  },
  {
    id: "msg-008",
    conversationId: "conv-1005",
    supplierId: "sup-001",
    type: "ai-interpretation",
    author: "ai",
    body: "AI detected conflicting delivery dates and a conditional full-pallet price. Bundle discount is missing.",
    sentiment: "risk",
    createdAt: "2026-04-19T08:12:00.000Z",
  },
  {
    id: "msg-inv-1001",
    conversationId: "conv-1001",
    supplierId: "sup-001",
    type: "supplier-message",
    author: "supplier",
    body: "Attached the invoice for the agreed 1,200 cases. Please confirm remittance against Chase account.",
    sentiment: "neutral",
    createdAt: "2026-04-19T07:18:00.000Z",
    attachmentType: "pdf",
    attachmentLabel: "NSF-48291-april-replenishment.pdf",
    invoiceId: "inv-7001",
  },
  {
    id: "msg-inv-1002",
    conversationId: "conv-1002",
    supplierId: "sup-002",
    type: "supplier-message",
    author: "supplier",
    body: "Invoice for the split shipment attached. Freight surcharge is itemized separately.",
    sentiment: "risk",
    createdAt: "2026-04-19T05:50:00.000Z",
    attachmentType: "pdf",
    attachmentLabel: "HBC-18044-split-shipment.pdf",
    invoiceId: "inv-7002",
  },
  {
    id: "msg-zh-1003-a",
    conversationId: "conv-1003",
    supplierId: "sup-003",
    type: "supplier-message",
    author: "supplier",
    body: "关于双十一档期,我们这边已经预留了 900 箱多谷物饼干,计划在第 46 周发货。单价维持 $9.58/箱,付款条件 Net 30。请确认这边的分配,发票按老账户汇款即可。",
    sentiment: "positive",
    createdAt: "2026-04-17T11:20:00.000Z",
    language: "ZH",
    translation:
      "Regarding 11.11 campaign, we have reserved 900 cartons of multigrain crackers, scheduled to ship in week 46. Unit price stays at $9.58/carton, payment terms Net 30. Please confirm the allocation; invoice will be remitted to the existing account.",
  },
  {
    id: "msg-zh-1003-b",
    conversationId: "conv-1003",
    supplierId: "sup-003",
    type: "ai-interpretation",
    author: "ai",
    body: "Translated from 中文: Supplier confirms 900 cartons reserved for 11.11, week 46 delivery, $9.58/carton, Net 30. Intent = accept allocation. Missing field: exact ship date within week 46.",
    sentiment: "positive",
    createdAt: "2026-04-17T11:22:00.000Z",
    language: "EN",
  },
  {
    id: "msg-zh-1003-c",
    conversationId: "conv-1003",
    supplierId: "sup-003",
    type: "merchant-action",
    author: "ai",
    body: "收到,确认保留 900 箱至双十一档期。请在第 46 周发运前 7 天提供准确发运日期。发票请开至 Pacific Snacks Supply 原账户 Bank of America **** 1180,付款条件 Net 30 照旧。",
    sentiment: "neutral",
    createdAt: "2026-04-17T11:25:00.000Z",
    language: "ZH",
    translation:
      "Confirmed, reserving 900 cartons for the 11.11 campaign. Please provide the exact shipping date 7 days before dispatch in week 46. Invoice to existing Pacific Snacks Supply account Bank of America **** 1180, Net 30 terms unchanged.",
  },
  {
    id: "msg-inv-1003",
    conversationId: "conv-1003",
    supplierId: "sup-003",
    type: "supplier-message",
    author: "supplier",
    body: "已附上第 46 周促销档期的发票,金额与先前锁定一致,汇款账户与结算包保持不变。请查收确认。",
    sentiment: "positive",
    createdAt: "2026-04-18T22:40:00.000Z",
    attachmentType: "pdf",
    attachmentLabel: "PSS-92018-promo-reserve.pdf",
    invoiceId: "inv-7003",
    language: "ZH",
    translation:
      "Invoice for the week 46 promo campaign is attached. Amount matches the prior lock and remittance account is unchanged from the settlement packet. Please review and confirm.",
  },
  {
    id: "msg-ja-1004-a",
    conversationId: "conv-1004",
    supplierId: "sup-004",
    type: "supplier-message",
    author: "supplier",
    body: "MOQ の例外承認について、620 パックで対応可能です。納期は 4 月 28 日、単価は $12.20、支払条件は Net 30 となります。請求書は承認済み MOQ シートと併せて送付いたします。",
    sentiment: "positive",
    createdAt: "2026-04-16T09:15:00.000Z",
    language: "JA",
    translation:
      "We can accommodate the MOQ exception at 620 packs. Delivery April 28, unit price $12.20, payment terms Net 30. Invoice will be sent together with the approved MOQ sheet.",
  },
  {
    id: "msg-ja-1004-b",
    conversationId: "conv-1004",
    supplierId: "sup-004",
    type: "ai-interpretation",
    author: "ai",
    body: "Translated from 日本語: Supplier accepts the MOQ exception at 620 packs, delivery Apr 28, $12.20/pack, Net 30. No missing fields detected. Confidence 96%.",
    sentiment: "positive",
    createdAt: "2026-04-16T09:17:00.000Z",
    language: "EN",
  },
  {
    id: "msg-ja-1004-c",
    conversationId: "conv-1004",
    supplierId: "sup-004",
    type: "merchant-action",
    author: "ai",
    body: "承知いたしました。MOQ 例外の 620 パックで発注を進めます。4 月 28 日の納期と単価 $12.20、支払条件 Net 30 で合意します。請求書送付時に銀行情報(Evergreen マスター登録口座)と整合するようご確認ください。",
    sentiment: "neutral",
    createdAt: "2026-04-16T09:20:00.000Z",
    language: "JA",
    translation:
      "Understood. We will proceed with the MOQ exception of 620 packs. Agreeing to April 28 delivery, unit price $12.20, payment terms Net 30. When sending the invoice, please confirm the bank information matches the master Evergreen account on file.",
  },
  {
    id: "msg-inv-1004",
    conversationId: "conv-1004",
    supplierId: "sup-004",
    type: "supplier-message",
    author: "supplier",
    body: "MOQ 例外発注分の請求書を画像でお送りいたします。承認済み MOQ シートと併せてご確認ください。単価・数量・支払条件はご相談の通りです。",
    sentiment: "risk",
    createdAt: "2026-04-18T17:35:00.000Z",
    attachmentType: "image",
    attachmentLabel: "EHG-55107-moq-sheet.jpg",
    invoiceId: "inv-7004",
    language: "JA",
    translation:
      "Sending the invoice for the MOQ exception order as an image. Please review it together with the approved MOQ sheet. Unit price, quantity, and payment terms are as discussed.",
  },
]

export const mockInvoices: Invoice[] = [
  {
    id: "inv-7001",
    supplierId: "sup-001",
    productSku: "SKU-ALM-8842",
    linkedSkus: ["SKU-ALM-8842", "SKU-RCE-7740"],
    workflowId: "wf-1002",
    invoiceNumber: "NSF-48291",
    amount: 48240,
    negotiatedAmount: 48000,
    expectedQuantity: 1200,
    invoiceQuantity: 1200,
    unitPrice: 40.2,
    subtotal: 48240,
    currency: "USD",
    risk: "waiting approval",
    riskLevel: "Low Risk",
    riskReason: "Amount variance is within tolerance and supplier identity matches.",
    validationStatus: "Validated",
    approvalState: "Waiting Approval",
    sourceType: "PDF",
    fileName: "NSF-48291-april-replenishment.pdf",
    fileSize: "248 KB",
    bankDetails: "Chase **** 4412",
    paymentTerms: "Net 30",
    riskConfidence: 93,
    flags: {
      bankDetailsIssue: false,
      amountMismatch: false,
      missingFields: false,
      supplierInconsistency: false,
    },
    issueSummaries: [],
    mismatches: [],
    history: [
      {
        timestamp: "2026-04-19T07:20:00.000Z",
        title: "Invoice parsed",
        description: "Z.AI extracted line items and supplier remittance details.",
      },
      {
        timestamp: "2026-04-19T07:28:00.000Z",
        title: "Validation passed",
        description: "Matched against negotiated quantity and supplier profile.",
      },
    ],
    notes: "Safe to approve after merchant confirms restock packet.",
    status: "pending",
    dueDate: "2026-04-27",
    lastUpdated: "2026-04-19T07:28:00.000Z",
  },
  {
    id: "inv-7002",
    supplierId: "sup-002",
    productSku: "SKU-CFE-1290",
    linkedSkus: ["SKU-CFE-1290"],
    workflowId: "wf-1003",
    invoiceNumber: "HBC-18044",
    amount: 19780,
    negotiatedAmount: 18400,
    expectedQuantity: 480,
    invoiceQuantity: 480,
    unitPrice: 41.21,
    subtotal: 19780,
    currency: "USD",
    risk: "needs review",
    riskLevel: "High Risk",
    riskReason: "Freight charge is not capped and total exceeds negotiated amount.",
    validationStatus: "Mismatch Detected",
    approvalState: "Needs Review",
    sourceType: "Email Attachment",
    fileName: "HBC-18044-split-shipment.pdf",
    fileSize: "312 KB",
    bankDetails: "Wells Fargo **** 9088",
    paymentTerms: "Net 15",
    riskConfidence: 89,
    flags: {
      bankDetailsIssue: false,
      amountMismatch: true,
      missingFields: true,
      supplierInconsistency: false,
    },
    issueSummaries: [
      "Invoice total exceeds negotiated amount by $1,380",
      "Freight cap missing from supplier conversation",
    ],
    mismatches: [
      "Invoice total exceeds negotiated amount by $1,380",
      "Freight cap missing from supplier conversation",
    ],
    history: [
      {
        timestamp: "2026-04-19T05:55:00.000Z",
        title: "Invoice parsed",
        description: "Split shipment invoice attached from supplier chat follow-up.",
      },
      {
        timestamp: "2026-04-19T06:04:00.000Z",
        title: "Mismatch detected",
        description: "Freight and total amount require review before approval.",
      },
    ],
    notes: "Hold until Harbor Beverage confirms freight cap.",
    status: "exception",
    dueDate: "2026-04-24",
    lastUpdated: "2026-04-19T06:04:00.000Z",
  },
  {
    id: "inv-7003",
    supplierId: "sup-003",
    productSku: "SKU-SNP-4471",
    linkedSkus: ["SKU-SNP-4471"],
    workflowId: "wf-1001",
    invoiceNumber: "PSS-92018",
    amount: 12860,
    negotiatedAmount: 12860,
    expectedQuantity: 900,
    invoiceQuantity: 900,
    unitPrice: 14.29,
    subtotal: 12860,
    currency: "USD",
    risk: "low risk",
    riskLevel: "Low Risk",
    riskReason: "Invoice matches expected allocation and bank details are verified.",
    validationStatus: "Validated",
    approvalState: "Completed",
    sourceType: "PDF",
    fileName: "PSS-92018-promo-reserve.pdf",
    fileSize: "190 KB",
    bankDetails: "Bank of America **** 1180",
    paymentTerms: "Net 30",
    riskConfidence: 97,
    flags: {
      bankDetailsIssue: false,
      amountMismatch: false,
      missingFields: false,
      supplierInconsistency: false,
    },
    issueSummaries: [],
    mismatches: [],
    history: [
      {
        timestamp: "2026-04-18T22:45:00.000Z",
        title: "Invoice matched",
        description: "Validated against promo reserve allocation.",
      },
      {
        timestamp: "2026-04-19T01:10:00.000Z",
        title: "Marked completed",
        description: "Settlement packet closed.",
      },
    ],
    notes: "Completed and archived.",
    status: "paid",
    dueDate: "2026-05-02",
    lastUpdated: "2026-04-19T01:10:00.000Z",
  },
  {
    id: "inv-7004",
    supplierId: "sup-004",
    productSku: "SKU-LND-3021",
    linkedSkus: ["SKU-LND-3021"],
    workflowId: "wf-1003",
    invoiceNumber: "EHG-55107",
    amount: 22110,
    negotiatedAmount: 21000,
    expectedQuantity: 620,
    invoiceQuantity: 620,
    unitPrice: 35.66,
    subtotal: 22110,
    currency: "USD",
    risk: "blocked",
    riskLevel: "Medium Risk",
    riskReason: "MOQ exception accepted, but remittance details differ from supplier master.",
    validationStatus: "Missing Information",
    approvalState: "Blocked",
    sourceType: "Image",
    fileName: "EHG-55107-moq-sheet.jpg",
    fileSize: "1.1 MB",
    bankDetails: "Unverified account ending 3301",
    paymentTerms: "Due on receipt",
    riskConfidence: 82,
    flags: {
      bankDetailsIssue: true,
      amountMismatch: true,
      missingFields: true,
      supplierInconsistency: false,
    },
    issueSummaries: [
      "Bank details differ from supplier master",
      "Payment terms differ from accepted MOQ exception",
      "Subtotal exceeds negotiated amount by $1,110",
    ],
    mismatches: [
      "Bank details differ from supplier master",
      "Payment terms differ from accepted MOQ exception",
      "Subtotal exceeds negotiated amount by $1,110",
    ],
    history: [
      {
        timestamp: "2026-04-18T17:20:00.000Z",
        title: "Image invoice uploaded",
        description: "Supplier sent invoice image with MOQ sheet.",
      },
      {
        timestamp: "2026-04-18T17:44:00.000Z",
        title: "Blocked",
        description: "Remittance and payment terms require finance review.",
      },
    ],
    notes: "Do not approve until bank details are verified.",
    status: "blocked",
    dueDate: "2026-04-22",
    lastUpdated: "2026-04-18T17:44:00.000Z",
  },
]

export const mockWorkflows: Workflow[] = [
  {
    id: "wf-1001",
    title: "Promo reserve settlement review",
    stage: "ready for approval",
    status: "active",
    owner: "Nadia Chen",
    updatedAt: "2026-04-19T07:20:00.000Z",
  },
  {
    id: "wf-1002",
    title: "Northstar bundled replenishment",
    stage: "negotiation active",
    status: "blocked",
    owner: "Marcus Bell",
    updatedAt: "2026-04-19T06:05:00.000Z",
  },
  {
    id: "wf-1003",
    title: "April invoice exception review",
    stage: "invoice review",
    status: "pending",
    owner: "Priya Raman",
    updatedAt: "2026-04-18T22:45:00.000Z",
  },
]

export const dashboardKpis = [
  {
    title: "Low Stock Alerts",
    value: "4",
    change: "2 below current threshold",
    tone: "warning" as const,
  },
  {
    title: "Threshold Changes Today",
    value: "3",
    change: "Cold brew, rice, protein bars",
    tone: "ai" as const,
  },
  {
    title: "Open Conversations",
    value: "5",
    change: "2 need operator review",
    tone: "default" as const,
  },
  {
    title: "Invoices Waiting Approval",
    value: "1",
    change: "$48.2K pending",
    tone: "danger" as const,
  },
]

export const stockTrendData = [
  {
    date: "Apr 01",
    proteinBars: 720,
    proteinThreshold: 470,
    coldBrew: 310,
    coldBrewThreshold: 180,
    rice: 230,
    riceThreshold: 160,
  },
  {
    date: "Apr 04",
    proteinBars: 660,
    proteinThreshold: 480,
    coldBrew: 252,
    coldBrewThreshold: 188,
    rice: 198,
    riceThreshold: 165,
  },
  {
    date: "Apr 07",
    proteinBars: 612,
    proteinThreshold: 490,
    coldBrew: 220,
    coldBrewThreshold: 196,
    rice: 146,
    riceThreshold: 170,
  },
  {
    date: "Apr 10",
    proteinBars: 560,
    proteinThreshold: 505,
    coldBrew: 174,
    coldBrewThreshold: 204,
    rice: 121,
    riceThreshold: 175,
  },
  {
    date: "Apr 13",
    proteinBars: 505,
    proteinThreshold: 515,
    coldBrew: 138,
    coldBrewThreshold: 208,
    rice: 88,
    riceThreshold: 178,
  },
  {
    date: "Apr 16",
    proteinBars: 462,
    proteinThreshold: 520,
    coldBrew: 112,
    coldBrewThreshold: 210,
    rice: 70,
    riceThreshold: 180,
  },
  {
    date: "Apr 19",
    proteinBars: 418,
    proteinThreshold: 520,
    coldBrew: 96,
    coldBrewThreshold: 210,
    rice: 58,
    riceThreshold: 180,
  },
]

export const monthlyDemandData = [
  { month: "Jan", demand: 8400, promo: "Baseline" },
  { month: "Feb", demand: 9100, promo: "Payday Sale" },
  { month: "Mar", demand: 12600, promo: "Raya" },
  { month: "Apr", demand: 9800, promo: "Baseline" },
  { month: "May", demand: 10400, promo: "Baseline" },
  { month: "Jun", demand: 11200, promo: "Payday Sale" },
  { month: "Jul", demand: 10100, promo: "Baseline" },
  { month: "Aug", demand: 10900, promo: "Baseline" },
  { month: "Sep", demand: 11800, promo: "Payday Sale" },
  { month: "Oct", demand: 12100, promo: "Baseline" },
  { month: "Nov", demand: 15800, promo: "11.11" },
  { month: "Dec", demand: 13900, promo: "Holiday" },
]

export const workflowStatusDistribution = [
  { name: "Review needed", value: 9, color: "#F59E0B" },
  { name: "Negotiation active", value: 7, color: "#8B5CF6" },
  { name: "Invoice review", value: 5, color: "#3B82F6" },
  { name: "Ready for approval", value: 6, color: "#10B981" },
  { name: "Blocked", value: 3, color: "#EF4444" },
  { name: "Completed", value: 18, color: "#6B7280" },
]

export const invoiceRiskDistribution = [
  { name: "Low risk", count: 2, color: "#10B981" },
  { name: "Waiting approval", count: 1, color: "#3B82F6" },
  { name: "Needs review", count: 1, color: "#F59E0B" },
  { name: "Blocked", count: 1, color: "#EF4444" },
  { name: "Completed", count: 1, color: "#6B7280" },
]

export const attentionItems = [
  {
    sku: "SKU-CFE-1290",
    productName: "Cold Brew Concentrate 1L",
    supplier: "Harbor Beverage Co.",
    currentStock: 96,
    currentThreshold: 210,
    conversationStatus: "needs reply",
    invoiceStatus: "needs review",
    priority: "critical",
    action: "Auto Restock",
    href: "/conversations/conv-1002",
  },
  {
    sku: "SKU-RCE-7740",
    productName: "Jasmine Rice 5kg",
    supplier: "Northstar Foods",
    currentStock: 58,
    currentThreshold: 180,
    conversationStatus: "negotiating",
    invoiceStatus: "waiting approval",
    priority: "critical",
    action: "Auto Restock",
    href: "/conversations/conv-1005",
  },
  {
    sku: "SKU-ALM-8842",
    productName: "Almond Protein Bar 12ct",
    supplier: "Northstar Foods",
    currentStock: 418,
    currentThreshold: 520,
    conversationStatus: "negotiating",
    invoiceStatus: "waiting approval",
    priority: "high",
    action: "Auto Restock",
    href: "/conversations/conv-1001",
  },
  {
    sku: "SKU-LND-3021",
    productName: "Citrus Laundry Sheets 60ct",
    supplier: "Evergreen Household Goods",
    currentStock: 188,
    currentThreshold: 330,
    conversationStatus: "resolved",
    invoiceStatus: "blocked",
    priority: "high",
    action: "Unblock",
    href: "/invoice-management/inv-7004",
  },
]

export const insightCards = {
  thresholdRecommendation: {
    title: "Threshold Recommendation",
    value: "+18%",
    body: "Raise cold brew threshold from 178 to 210 units through May due to promo uplift and slower supplier lead time.",
  },
  recentSupplierActivity: [
    "Harbor Beverage proposed split shipment for Apr 23 and Apr 29.",
    "Northstar Foods accepted expedited protein bar quantity.",
    "Evergreen Household Goods requested MOQ exception approval.",
  ],
  approvalQueueSummary: {
    invoices: 1,
    thresholdChanges: 3,
    replenishmentOrders: 3,
  },
}

export const mockTimelineEvents: TimelineEvent[] = [
  {
    id: "evt-001",
    workflowId: "wf-1001",
    title: "Approval packet generated",
    description: "Z.AI assembled demand forecast, supplier terms, and invoice references.",
    timestamp: "2026-04-19T07:20:00.000Z",
    tone: "ai",
  },
  {
    id: "evt-002",
    workflowId: "wf-1002",
    title: "Supplier counteroffer flagged",
    description: "Pricing moved above tolerance and requires merchant review.",
    timestamp: "2026-04-19T06:05:00.000Z",
    tone: "warning",
  },
  {
    id: "evt-003",
    workflowId: "wf-1003",
    title: "Invoice variance detected",
    description: "Harbor Beverage invoice differs from expected freight charge.",
    timestamp: "2026-04-18T22:45:00.000Z",
    tone: "danger",
  },
  {
    id: "evt-004",
    workflowId: "wf-1001",
    title: "Threshold change queued",
    description: "Cold brew threshold increased for upcoming Payday Sale demand.",
    timestamp: "2026-04-18T18:10:00.000Z",
    tone: "ai",
  },
]

export const topSuppliersSummary = [
  {
    supplier: "Northstar Foods",
    openOrders: 8,
    reliability: 94,
    invoiceExposure: "$82.4K",
    tone: "success" as const,
  },
  {
    supplier: "Pacific Snacks Supply",
    openOrders: 5,
    reliability: 89,
    invoiceExposure: "$31.8K",
    tone: "success" as const,
  },
  {
    supplier: "Harbor Beverage Co.",
    openOrders: 6,
    reliability: 79,
    invoiceExposure: "$46.2K",
    tone: "warning" as const,
  },
]

export const inventorySummaryStats = [
  {
    title: "Total Active SKUs",
    value: "5",
    change: "4 suppliers tracked",
    tone: "default" as const,
  },
  {
    title: "Near Threshold",
    value: "1",
    change: "Protein bars",
    tone: "warning" as const,
  },
  {
    title: "Below Threshold",
    value: "2",
    change: "Requires restock",
    tone: "danger" as const,
  },
  {
    title: "Batch Restock Candidates",
    value: "1",
    change: "Same-supplier bundle",
    tone: "ai" as const,
  },
]

export const inventoryHealthDistribution = [
  { name: "Healthy", count: 1, color: "#10B981" },
  { name: "Near Threshold", count: 1, color: "#F59E0B" },
  { name: "Below Threshold", count: 2, color: "#EF4444" },
  { name: "Batch Candidate", count: 1, color: "#8B5CF6" },
]

export const supplierExposureData = [
  { supplier: "Northstar Foods", products: 2, color: "#3B82F6" },
  { supplier: "Harbor Beverage Co.", products: 1, color: "#F59E0B" },
  { supplier: "Pacific Snacks Supply", products: 1, color: "#10B981" },
  { supplier: "Evergreen Household Goods", products: 1, color: "#8B5CF6" },
]

export const productMonthlySummaryBySku = {
  "SKU-ALM-8842": [
    { month: "Jan", averageSales: 820, seasonalSpike: "Normal", promotionNote: "Baseline demand" },
    { month: "Feb", averageSales: 850, seasonalSpike: "Medium", promotionNote: "Payday Sale lift" },
    { month: "Mar", averageSales: 940, seasonalSpike: "High", promotionNote: "Raya pantry bundle" },
    { month: "Apr", averageSales: 680, seasonalSpike: "Normal", promotionNote: "Replenishment lag" },
  ],
  "SKU-CFE-1290": [
    { month: "Jan", averageSales: 360, seasonalSpike: "Normal", promotionNote: "Baseline demand" },
    { month: "Feb", averageSales: 400, seasonalSpike: "Medium", promotionNote: "Payday Sale lift" },
    { month: "Mar", averageSales: 430, seasonalSpike: "High", promotionNote: "Raya beverage bundle" },
    { month: "Apr", averageSales: 380, seasonalSpike: "High", promotionNote: "Supplier split delivery risk" },
  ],
  "SKU-SNP-4471": [
    { month: "Jan", averageSales: 710, seasonalSpike: "Normal", promotionNote: "Baseline demand" },
    { month: "Feb", averageSales: 735, seasonalSpike: "Medium", promotionNote: "Payday Sale lift" },
    { month: "Mar", averageSales: 760, seasonalSpike: "Medium", promotionNote: "Raya snack display" },
    { month: "Apr", averageSales: 610, seasonalSpike: "Normal", promotionNote: "Healthy stock cover" },
  ],
  "SKU-LND-3021": [
    { month: "Jan", averageSales: 360, seasonalSpike: "Normal", promotionNote: "Baseline demand" },
    { month: "Feb", averageSales: 395, seasonalSpike: "Medium", promotionNote: "Payday Sale lift" },
    { month: "Mar", averageSales: 450, seasonalSpike: "High", promotionNote: "Raya household refresh" },
    { month: "Apr", averageSales: 420, seasonalSpike: "Medium", promotionNote: "Bundle with same supplier" },
  ],
  "SKU-RCE-7740": [
    { month: "Jan", averageSales: 270, seasonalSpike: "Normal", promotionNote: "Baseline demand" },
    { month: "Feb", averageSales: 295, seasonalSpike: "Medium", promotionNote: "Payday Sale lift" },
    { month: "Mar", averageSales: 335, seasonalSpike: "High", promotionNote: "Raya pantry spike" },
    { month: "Apr", averageSales: 290, seasonalSpike: "High", promotionNote: "Below current threshold" },
  ],
}

export const thresholdAnalysisBySku = {
  "SKU-ALM-8842": {
    currentThreshold: 520,
    recommendedThreshold: 610,
    confidenceScore: 91,
    explanation:
      "Demand is trending above the current threshold and supplier lead time is stable, so Z.AI recommends lifting the reorder threshold before the next Payday Sale.",
  },
  "SKU-CFE-1290": {
    currentThreshold: 210,
    recommendedThreshold: 260,
    confidenceScore: 94,
    explanation:
      "Current stock is below the current threshold while demand remains elevated. Split delivery terms increase risk, so immediate supplier conversation is recommended.",
  },
  "SKU-SNP-4471": {
    currentThreshold: 560,
    recommendedThreshold: 540,
    confidenceScore: 87,
    explanation:
      "Stock remains healthy against forecast demand. Z.AI recommends only a small reserve adjustment for the next promotion cycle.",
  },
  "SKU-LND-3021": {
    currentThreshold: 330,
    recommendedThreshold: 390,
    confidenceScore: 89,
    explanation:
      "Stock is under the current threshold and shares supplier capacity with other household goods, making this a strong batch restock candidate.",
  },
  "SKU-RCE-7740": {
    currentThreshold: 180,
    recommendedThreshold: 240,
    confidenceScore: 93,
    explanation:
      "Stock is well below the current threshold with seasonal pantry demand still elevated after Raya. Z.AI recommends bundling with Northstar Foods items.",
  },
}

export const supplierBatchAdvantageNotes = {
  "sup-001":
    "Combining pantry and packaged goods improves pallet utilization and reduces landed freight cost by an estimated 7%.",
  "sup-002":
    "Batching is limited by beverage lead time, but split delivery can protect service level for fast-moving SKUs.",
  "sup-003":
    "Supplier has healthy availability, so bundle only if promotion reserve needs to be secured early.",
  "sup-004":
    "Household goods can be bundled under the same MOQ exception to reduce approval cycles.",
}

export const restockRecommendations: RestockRecommendation[] = [
  {
    id: "restock-1002",
    sku: "SKU-CFE-1290",
    productName: "Cold Brew Concentrate 1L",
    supplier: "Harbor Beverage Co.",
    reason: "Current stock is below the current threshold and 30D demand is declining stock coverage faster than lead time can recover.",
    currentStock: 96,
    currentThreshold: 210,
    targetPrice: "$21.90 - $22.50 per unit",
    quantity: 480,
    estimatedSpend: "$10.8K",
    conversationId: "conv-1002",
    automationPlan: [
      "Open supplier negotiation with target price and freight cap",
      "Confirm split delivery dates and shipment quantities",
      "Create replenishment order after supplier confirms terms",
      "Route invoice for exception review only if freight exceeds cap",
    ],
  },
  {
    id: "restock-1005",
    sku: "SKU-RCE-7740",
    productName: "Jasmine Rice 5kg",
    supplier: "Northstar Foods",
    reason: "Stock is critically below current threshold and can be bundled with protein bars for better pallet utilization.",
    currentStock: 58,
    currentThreshold: 180,
    targetPrice: "$15.80 - $16.25 per bag",
    quantity: 700,
    estimatedSpend: "$11.3K",
    conversationId: "conv-1005",
    automationPlan: [
      "Bundle rice with Northstar Foods protein bar shipment",
      "Negotiate delivery date conflict from voice note",
      "Lock full-pallet price if bundle discount is confirmed",
      "Generate purchase order and keep merchant notified",
    ],
  },
  {
    id: "restock-1001",
    sku: "SKU-ALM-8842",
    productName: "Almond Protein Bar 12ct",
    supplier: "Northstar Foods",
    reason: "Stock is approaching the current threshold before Payday Sale uplift.",
    currentStock: 418,
    currentThreshold: 520,
    targetPrice: "$17.90 - $18.25 per case",
    quantity: 1200,
    estimatedSpend: "$21.9K",
    conversationId: "conv-1001",
    automationPlan: [
      "Negotiate expedited quantity with existing supplier thread",
      "Hold target case price under threshold recommendation",
      "Bundle freight with Jasmine Rice if supplier confirms pallet space",
      "Prepare order packet for autonomous procurement tracking",
    ],
  },
]

export const invoiceSummaryStats = [
  {
    title: "Waiting Approval",
    value: "1",
    change: "$48.2K ready",
    tone: "ai" as const,
  },
  {
    title: "Needs Review",
    value: "1",
    change: "Amount mismatch",
    tone: "warning" as const,
  },
  {
    title: "Blocked",
    value: "1",
    change: "Bank details issue",
    tone: "danger" as const,
  },
  {
    title: "Completed",
    value: "1",
    change: "$12.9K closed",
    tone: "success" as const,
  },
]

export const invoiceRiskLevelDistribution = [
  { name: "Low Risk", count: 2, color: "#10B981" },
  { name: "Medium Risk", count: 1, color: "#F59E0B" },
  { name: "High Risk", count: 1, color: "#EF4444" },
]

export const approvalPipelineDistribution = [
  { name: "Waiting Approval", count: 1, color: "#3B82F6" },
  { name: "Needs Review", count: 1, color: "#F59E0B" },
  { name: "Blocked", count: 1, color: "#EF4444" },
  { name: "Completed", count: 1, color: "#10B981" },
]

export const supplierInvoiceVolume = [
  { supplier: "Northstar Foods", invoices: 1, color: "#3B82F6" },
  { supplier: "Harbor Beverage Co.", invoices: 1, color: "#F59E0B" },
  { supplier: "Pacific Snacks Supply", invoices: 1, color: "#10B981" },
  { supplier: "Evergreen Household Goods", invoices: 1, color: "#8B5CF6" },
]

export const thresholdChangeRequests: ThresholdChangeRequest[] = [
  {
    id: "thr-001",
    productSku: "SKU-CFE-1290",
    productName: "Cold Brew Concentrate 1L",
    currentThreshold: 210,
    proposedThreshold: 240,
    changePercent: 14,
    reason:
      "Hot season uplift + Harbor Beverage lead time slipped to 8 days. Raise threshold to cover the 2-day buffer.",
    proposedAt: "2026-04-19T05:12:00.000Z",
    status: "pending",
    trigger: "lead-time-shift",
  },
  {
    id: "thr-002",
    productSku: "SKU-ALM-8842",
    productName: "Almond Protein Bar 12ct",
    currentThreshold: 520,
    proposedThreshold: 490,
    changePercent: -6,
    reason:
      "30D velocity dropped 18% post-promo. Lowering threshold frees ~$550 of working capital without stockout risk.",
    proposedAt: "2026-04-19T06:40:00.000Z",
    status: "pending",
    trigger: "demand-drop",
  },
  {
    id: "thr-003",
    productSku: "SKU-RCE-7740",
    productName: "Jasmine Rice 5kg",
    currentThreshold: 180,
    proposedThreshold: 220,
    changePercent: 22,
    reason:
      "Bundle window with Northstar Foods PO. Raising threshold unlocks pallet discount on Almond + Rice bundle.",
    proposedAt: "2026-04-19T07:55:00.000Z",
    status: "pending",
    trigger: "bundle-opportunity",
  },
  {
    id: "thr-004",
    productSku: "SKU-SNP-4471",
    productName: "Sea Salt Plantain Chips",
    currentThreshold: 560,
    proposedThreshold: 610,
    changePercent: 9,
    reason:
      "Multigrain crackers promo Q2 historically lifts sibling snack SKUs 8–11%. Small buffer increase recommended.",
    proposedAt: "2026-04-18T22:05:00.000Z",
    status: "pending",
    trigger: "demand-spike",
  },
]
